# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dnyanu\OneDrive\Desktop\studentform.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector

import sys
import MySQLdb as mdb
# noinspection PyInterpreter
class Ui_MainWindow(object):
    def messagebox(self, title, message):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(msg)
        msg.setStandardButtons(QtWidgets.QMessageBox.ok)
        msg.exec_()

    def alertmsg(self,title,Message):
        warn = QtWidgets.QMessageBox()
        warn.setIcon(QtWidgets.QMessageBox.Information)
        warn.setWindowTitle(title)
        warn.setText(Message)
        warn.setStandardButtons(QtWidgets.QMessageBox.Ok)
        warn.exec_()
          # QtWidgets.QMessageBox.about(self, "Title", "Message")



    def Register(self):
      
                                                                 
        v=self.lineEdit.text()
        if v =='' or v=="null":
            self.alertmsg("error","Please Fill The Student Name")
        else:
            print("STUDENT NAME  :",v)
        v2=self.lineEdit_2.text()
        self.lineEdit_2.setMaxLength(2)      
        self.lineEdit_2.setValidator(QtGui.QIntValidator())
        if v2 == '' or v2 == "null":
            self.alertmsg("error", "Please Mentioned your Age")


        else:
            print("AGE           :", v2)

        v3=self.lineEdit_3.text()
        if v3 == '' or v3 == "null":
            self.alertmsg("error", "Please Fill The Address")
        else:
            print("ADDRESS       :", v3)

        v4=self.comboBox.currentText()

        if v4 == '' or v4 == "null":
            self.alertmsg("error", "Please Select The Gender")
        else:
            print("GENDER       :", v4)

        v5=self.lineEdit_4.text()
        self.lineEdit_4.setMaxLength(10)
        self.lineEdit_4.setValidator(QtGui.QIntValidator())
        if v5 == '' or v5 == "null"  :
            self.alertmsg("error", "Please Enter Your Mobile Number")
        else:
            print("MOBILE_NO.       :", v5)



        mydb = mysql.connector.connect(host="localhost", user="root", password="root", database='testapp')
        cursor = mydb.cursor()

        aaa = "INSERT INTO register(sname, age, adrs, gend, mno) VALUES (%s, %s, %s, %s, %s)"
        val = (v,v2,v3,v4,v5)
        cursor.execute(aaa, val)
        mydb.commit()
        print(cursor.rowcount,"Successfully Inserted ")
        cursor.close()
        mydb.close()






        #mydb=mysql.connector.connect(host="localhost",user="root",password="root",database="testapp")
        ####conn=pymysql.connect(host="localhost",user="root",password="root",database="testapp")
        #mycursor=mydb.cursor()
        #mysql="insert into register(sname,age,adrs,gend,mno) values(%s,%s,%s,%s,%s)"
        #val=(v,v2,v3,v4,v5)
        #mycursor.execute(mysql,val)
        #mydb.commit()
        #print(mycursor.rowcount,"Inserted")


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton_2.clicked.connect(self.)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 280, 131, 41))
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 90, 131, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 130, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 160, 91, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 100, 141, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 130, 141, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(310, 160, 141, 22))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(180, 0, 381, 61))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(210, 190, 71, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 220, 101, 31))
        self.label_6.setObjectName("label_6")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(310, 230, 141, 22))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 340, 801, 221))
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 200, 141, 22))
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")

        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton_2.clicked.connect(self.Register)




    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Register"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Student_name :</span></p></body></html>"))


        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Age :</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Address :</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Student Registration Form</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Gender :</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Mob_No. :</span></p></body></html>"))

        self.comboBox.setItemText(0, _translate("MainWindow", "    "))
        self.comboBox.setItemText(1, _translate("MainWindow", "Male"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Female"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Other"))



    
                
     




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    #msgBox.exec_()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
